//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Party_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_details
    {
        public int id { get; set; }
        public string party_type { get; set; }
        public Nullable<System.DateTime> party_time { get; set; }
        public Nullable<int> Number_of_attendees { get; set; }
    }
}
